"""Render the executor shim's Python source into the Mojo constant the binary embeds.

    python3 scripts/render_shim.py            # rewrite packages/m0-wsgi/src/shim_source.mojo
    python3 scripts/render_shim.py --check    # exit 1 if the rendered file is stale
    python3 scripts/render_shim.py --selftest # prove --check can fail

The shim -- the Python program that hosts a WSGI or ASGI application inside
`m0serve` -- has ONE source of truth, ``packages/m0-wsgi/shim/m0_shim.py``.
It is an ordinary Python file: editors, pyflakes and ``poe test-shim`` read
it as one. But the binary must not locate a file at run time relative to
itself (an unforced deployment failure; bridge.mojo says why), and Mojo has
no ``include_str``, so the file is rendered into a Mojo string constant,
``SHIM_SOURCE`` in ``packages/m0-wsgi/src/shim_source.mojo``, which
``bridge.mojo`` imports and ``exec``s into a fresh namespace per bridge.
The rendered file is committed, because ``mojo precompile src`` must see it;
``--check`` runs inside ``poe check-docs`` (so on every pull request, doc-only
ones included) and fails when the rendering is older than its source.

The rendering is one escape, applied in one direction: a backslash in the
Python becomes ``\\\\`` in the Mojo literal, so that Mojo's own unescaping --
which turns ``\\n`` into a newline and ``\\x01`` into a control byte -- hands the
interpreter the Python text byte for byte. Nothing else in a Mojo
triple-quoted literal is special except the closing quotes, so a ``\"\"\"`` in
the Python is refused rather than escaped. ``--check`` proves the round trip
as well as the freshness: the rendered literal, unescaped the way the
compiler unescapes it, must equal the ``.py`` -- which is what lets
``scripts/shim_ownership.py`` test the ``.py`` and still be testing the
program the binary runs.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "packages" / "m0-wsgi" / "shim" / "m0_shim.py"
TARGET = REPO / "packages" / "m0-wsgi" / "src" / "shim_source.mojo"

_OPEN = 'comptime SHIM_SOURCE = """'
_CLOSE = '\n"""\n'

HEADER = '''"""The executor shim, as the Mojo string constant the binary embeds.

GENERATED by scripts/render_shim.py from packages/m0-wsgi/shim/m0_shim.py.
Do not edit this file: edit the `.py` and run `uv run poe render-shim`.
`poe check-docs` fails when this rendering is older than its source, and
the round trip (this literal, unescaped as the compiler unescapes it, is
the `.py` byte for byte) is checked at the same time. `bridge.mojo`
imports `SHIM_SOURCE` from here and `exec`s it into a fresh namespace per
`PyBridge`; `scripts/shim_ownership.py` (`poe test-shim`) drives the `.py`
directly.
"""

'''

# Mojo's escape set, the inverse of `escape` below, so --check can prove the
# rendered literal decodes to the source. Anything else backslash-prefixed
# in a RENDERED file is an error rather than a silent divergence.
_ESCAPES = {
    "\\": "\\", '"': '"', "'": "'", "n": "\n", "r": "\r",
    "t": "\t", "0": "\0",
}


def escape(text):
    """The Python text as it must appear inside the Mojo literal."""
    if '"""' in text:
        raise ValueError(
            "the shim source contains a triple double-quote, which would end "
            "the Mojo literal; use ''' for docstrings there")
    if "\r" in text:
        raise ValueError("the shim source contains a carriage return")
    return text.replace("\\", "\\\\")


def unescape(text, where="SHIM_SOURCE"):
    """What the compiler hands the interpreter for a rendered literal."""
    out = []
    i = 0
    while i < len(text):
        c = text[i]
        if c != "\\":
            out.append(c)
            i += 1
            continue
        if i + 1 >= len(text):
            raise ValueError("%s: trailing backslash" % where)
        nxt = text[i + 1]
        if nxt in _ESCAPES:
            out.append(_ESCAPES[nxt])
            i += 2
        elif nxt == "x":
            out.append(chr(int(text[i + 2:i + 4], 16)))
            i += 4
        else:
            raise ValueError(
                "%s: unsupported Mojo escape '\\%s'" % (where, nxt))
    return "".join(out)


def render(source_text):
    """The whole `shim_source.mojo` for a given `.py` text."""
    if not source_text.endswith("\n"):
        raise ValueError("the shim source must end with a newline")
    return HEADER + _OPEN + "\n" + escape(source_text) + '"""\n'


def extract(rendered):
    """The Python text a rendered file embeds -- the binary's program."""
    start = rendered.index(_OPEN) + len(_OPEN)
    end = rendered.index(_CLOSE, start)
    # The literal opens with a newline the renderer added; the program
    # proper starts after it.
    return unescape(rendered[start:end + 1])[1:]


def stale(source_text, rendered_text):
    """Why `rendered_text` is not the rendering of `source_text`, or None."""
    if rendered_text != render(source_text):
        return ("packages/m0-wsgi/src/shim_source.mojo is not the rendering "
                "of packages/m0-wsgi/shim/m0_shim.py -- run "
                "`uv run poe render-shim` and commit the result")
    if extract(rendered_text) != source_text:
        return ("the rendered SHIM_SOURCE does not decode back to "
                "m0_shim.py: the escaping is not a round trip")
    return None


def selftest():
    source = SOURCE.read_text(encoding="utf-8")
    rendered = render(source)
    ok = True

    def report(label, caught):
        nonlocal ok
        print("  %-15s %s" % ("caught" if caught else "MISSED", label))
        ok &= caught

    report("(control: the real source renders current)",
           stale(source, rendered) is None)
    report("an edited .py that was not re-rendered",
           stale(source + "\n# an edit\n", rendered) is not None)
    report("a rendered file edited by hand",
           stale(source, rendered.replace("_app = None", "_app = 0", 1))
           is not None)
    tricky = "x = b'\\x01' + '\\n'.encode()  # backslashes survive\n"
    report("backslash escapes round-trip byte for byte",
           extract(render(tricky)) == tricky)
    try:
        render('s = """no"""\n')
        report("a triple double-quote in the source is refused", False)
    except ValueError:
        report("a triple double-quote in the source is refused", True)
    print("render_shim selftest: " + ("PASS" if ok else "FAIL"))
    return ok


def main():
    if "--selftest" in sys.argv:
        sys.exit(0 if selftest() else 1)
    source = SOURCE.read_text(encoding="utf-8")
    rendered = render(source)
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        why = stale(source, current)
        if why:
            print("render_shim --check: " + why)
            sys.exit(1)
        print("render_shim --check: shim_source.mojo is current")
        return
    TARGET.write_text(rendered, encoding="utf-8")
    print("rendered %s -> %s (%d lines of Python)"
          % (SOURCE.relative_to(REPO), TARGET.relative_to(REPO),
             source.count("\n")))


if __name__ == "__main__":
    main()
