"""Render the executor shim's Python source into the Mojo constant the binary embeds.

    python3 scripts/render_shim.py            # rewrite packages/m0-wsgi/src/shim_source.mojo
    python3 scripts/render_shim.py --check    # exit 1 if the rendered file is stale
    python3 scripts/render_shim.py --selftest # prove --check can fail

The shim -- the Python program that hosts a WSGI or ASGI application inside
`m0serve` -- has ONE source of truth, ``packages/m0-wsgi/shim/m0_shim.py``.
It is an ordinary Python file: editors, pyflakes and ``poe test-shim`` read
it as one. But the binary must not locate a file at run time relative to
itself (an unforced deployment failure; bridge.mojo says why), and Mojo has
no ``include_str``, so the file is rendered into a Mojo string constant,
``SHIM_SOURCE`` in ``packages/m0-wsgi/src/shim_source.mojo``, which
``bridge.mojo`` imports and ``exec``s into a fresh namespace per bridge.
The rendered file is committed, because ``mojo precompile src`` must see it;
``--check`` runs inside ``poe check-docs`` (so on every pull request, doc-only
ones included) and fails when the rendering is older than its source.

The rendering is one escape, applied in one direction: a backslash in the
Python becomes ``\\\\`` in the Mojo literal, so that Mojo's own unescaping --
which turns ``\\n`` into a newline and ``\\x01`` into a control byte -- hands the
interpreter the Python text byte for byte. Nothing else in a Mojo
triple-quoted literal is special except the closing quotes, so a ``\"\"\"`` in
the Python is refused rather than escaped. ``--check`` proves the round trip
as well as the freshness: the rendered literal, unescaped the way the
compiler unescapes it, must equal the ``.py`` -- which is what lets
``scripts/shim_ownership.py`` test the ``.py`` and still be testing the
program the binary runs.

``--check`` holds one more thing: the numbers the shim MIRRORS. The shim
cannot import Mojo, so a size the Mojo side owns -- the largest datagram a
submit lane carries, the header before an inbound WebSocket message, the
inbound window -- is a module constant in the ``.py``, and ``MIRRORED``
names each one's source. A drift is a read that truncates a message or a
credit window that never refills, with nothing failing at the time; the
check fails naming the pair instead. ``--selftest`` drifts each side of
each pair, and removes each constant, and insists every one is caught.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "packages" / "m0-wsgi" / "shim" / "m0_shim.py"
TARGET = REPO / "packages" / "m0-wsgi" / "src" / "shim_source.mojo"

# (shim constant, Mojo source file, Mojo constant): each number the shim
# mirrors, and where the Mojo side defines it. Both sides must be a plain
# integer literal on a line of its own, so the check reads them without
# evaluating anything.
MIRRORED = [
    ("_WS_DATAGRAM_MAX", "packages/m0-http/lightbug_http/offload.mojo",
     "WS_DATAGRAM_MAX"),
    ("_WS_TAG_HEADER", "packages/m0-wsgi/src/handler.mojo", "WS_TAG_HEADER"),
    ("_WS_IN_WINDOW", "packages/m0-wsgi/src/handler.mojo", "WS_IN_WINDOW"),
]

_OPEN = 'comptime SHIM_SOURCE = """'
_CLOSE = '\n"""\n'

HEADER = '''"""The executor shim, as the Mojo string constant the binary embeds.

GENERATED by scripts/render_shim.py from packages/m0-wsgi/shim/m0_shim.py.
Do not edit this file: edit the `.py` and run `uv run poe render-shim`.
`poe check-docs` fails when this rendering is older than its source, and
the round trip (this literal, unescaped as the compiler unescapes it, is
the `.py` byte for byte) is checked at the same time. `bridge.mojo`
imports `SHIM_SOURCE` from here and `exec`s it into a fresh namespace per
`PyBridge`; `scripts/shim_ownership.py` (`poe test-shim`) drives the `.py`
directly.
"""

'''

# Mojo's escape set, the inverse of `escape` below, so --check can prove the
# rendered literal decodes to the source. Anything else backslash-prefixed
# in a RENDERED file is an error rather than a silent divergence.
_ESCAPES = {
    "\\": "\\", '"': '"', "'": "'", "n": "\n", "r": "\r",
    "t": "\t", "0": "\0",
}


def escape(text):
    """The Python text as it must appear inside the Mojo literal."""
    if '"""' in text:
        raise ValueError(
            "the shim source contains a triple double-quote, which would end "
            "the Mojo literal; use ''' for docstrings there")
    if "\r" in text:
        raise ValueError("the shim source contains a carriage return")
    return text.replace("\\", "\\\\")


def unescape(text, where="SHIM_SOURCE"):
    """What the compiler hands the interpreter for a rendered literal."""
    out = []
    i = 0
    while i < len(text):
        c = text[i]
        if c != "\\":
            out.append(c)
            i += 1
            continue
        if i + 1 >= len(text):
            raise ValueError("%s: trailing backslash" % where)
        nxt = text[i + 1]
        if nxt in _ESCAPES:
            out.append(_ESCAPES[nxt])
            i += 2
        elif nxt == "x":
            out.append(chr(int(text[i + 2:i + 4], 16)))
            i += 4
        else:
            raise ValueError(
                "%s: unsupported Mojo escape '\\%s'" % (where, nxt))
    return "".join(out)


def render(source_text):
    """The whole `shim_source.mojo` for a given `.py` text."""
    if not source_text.endswith("\n"):
        raise ValueError("the shim source must end with a newline")
    return HEADER + _OPEN + "\n" + escape(source_text) + '"""\n'


def extract(rendered):
    """The Python text a rendered file embeds -- the binary's program."""
    start = rendered.index(_OPEN) + len(_OPEN)
    end = rendered.index(_CLOSE, start)
    # The literal opens with a newline the renderer added; the program
    # proper starts after it.
    return unescape(rendered[start:end + 1])[1:]


def stale(source_text, rendered_text):
    """Why `rendered_text` is not the rendering of `source_text`, or None."""
    if rendered_text != render(source_text):
        return ("packages/m0-wsgi/src/shim_source.mojo is not the rendering "
                "of packages/m0-wsgi/shim/m0_shim.py -- run "
                "`uv run poe render-shim` and commit the result")
    if extract(rendered_text) != source_text:
        return ("the rendered SHIM_SOURCE does not decode back to "
                "m0_shim.py: the escaping is not a round trip")
    return None


def _int_constant(text, pattern, name):
    """The integer `pattern` binds `name` to in `text`, or None."""
    found = re.findall(pattern % re.escape(name), text, re.MULTILINE)
    if len(found) != 1:
        return None
    return int(found[0].replace("_", ""))


def mirror_drift(source_text, mojo_texts):
    """Why the shim's mirrored constants disagree with Mojo, or None.

    `mojo_texts` maps each file `MIRRORED` names to its text: a pure
    function of text, so the selftest can drift either side in memory."""
    problems = []
    for py_name, mojo_path, mojo_name in MIRRORED:
        py = _int_constant(source_text, r"^%s = ([0-9_]+)\s*$", py_name)
        mojo = _int_constant(
            mojo_texts.get(mojo_path, ""),
            r"^comptime %s = ([0-9_]+)\s*$", mojo_name)
        if py is None:
            problems.append("m0_shim.py does not define %s as one integer "
                            "literal" % py_name)
        elif mojo is None:
            problems.append("%s does not define %s as one integer literal"
                            % (mojo_path, mojo_name))
        elif py != mojo:
            problems.append("m0_shim.py's %s is %d but %s's %s is %d"
                            % (py_name, py, mojo_path, mojo_name, mojo))
    if problems:
        return ("the shim's mirrored constants disagree with their Mojo "
                "source: " + "; ".join(problems))
    return None


def _mojo_texts():
    return {path: (REPO / path).read_text(encoding="utf-8")
            for path in {m[1] for m in MIRRORED}}


def selftest():
    source = SOURCE.read_text(encoding="utf-8")
    rendered = render(source)
    ok = True

    def report(label, caught):
        nonlocal ok
        print("  %-15s %s" % ("caught" if caught else "MISSED", label))
        ok &= caught

    report("(control: the real source renders current)",
           stale(source, rendered) is None)
    report("an edited .py that was not re-rendered",
           stale(source + "\n# an edit\n", rendered) is not None)
    report("a rendered file edited by hand",
           stale(source, rendered.replace("_app = None", "_app = 0", 1))
           is not None)
    tricky = "x = b'\\x01' + '\\n'.encode()  # backslashes survive\n"
    report("backslash escapes round-trip byte for byte",
           extract(render(tricky)) == tricky)
    try:
        render('s = """no"""\n')
        report("a triple double-quote in the source is refused", False)
    except ValueError:
        report("a triple double-quote in the source is refused", True)
    mojo = _mojo_texts()
    report("(control: the mirrored constants agree)",
           mirror_drift(source, mojo) is None)
    for py_name, mojo_path, mojo_name in MIRRORED:
        py_line = re.search(r"^%s = [0-9_]+\s*$" % re.escape(py_name),
                            source, re.MULTILINE)
        mojo_line = re.search(
            r"^comptime %s = [0-9_]+\s*$" % re.escape(mojo_name),
            mojo[mojo_path], re.MULTILINE)
        if py_line is None or mojo_line is None:
            report("%s is found on both sides" % py_name, False)
            continue
        drifted = source.replace(py_line.group(0), py_name + " = 7", 1)
        report("%s drifted in the shim" % py_name,
               mirror_drift(drifted, mojo) is not None)
        other = dict(mojo)
        other[mojo_path] = mojo[mojo_path].replace(
            mojo_line.group(0), "comptime %s = 7" % mojo_name, 1)
        report("%s drifted in %s" % (mojo_name, mojo_path.split("/")[-1]),
               mirror_drift(source, other) is not None)
        gone = source.replace(py_line.group(0), "", 1)
        report("%s removed from the shim" % py_name,
               mirror_drift(gone, mojo) is not None)
    print("render_shim selftest: " + ("PASS" if ok else "FAIL"))
    return ok


def main():
    if "--selftest" in sys.argv:
        sys.exit(0 if selftest() else 1)
    source = SOURCE.read_text(encoding="utf-8")
    rendered = render(source)
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        why = stale(source, current) or mirror_drift(source, _mojo_texts())
        if why:
            print("render_shim --check: " + why)
            sys.exit(1)
        print("render_shim --check: shim_source.mojo is current, and the "
              "shim's mirrored constants agree")
        return
    TARGET.write_text(rendered, encoding="utf-8")
    print("rendered %s -> %s (%d lines of Python)"
          % (SOURCE.relative_to(REPO), TARGET.relative_to(REPO),
             source.count("\n")))


if __name__ == "__main__":
    main()
